
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 27 17:41:58 ART 2014
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 9;
  public static final int GTEQ = 20;
  public static final int STRING_LITERAL = 4;
  public static final int LKEY = 28;
  public static final int LBRACKET = 30;
  public static final int CHAR_LITERAL = 5;
  public static final int LTEQ = 19;
  public static final int UMINUS = 23;
  public static final int CONTINUE = 35;
  public static final int LPAREN = 26;
  public static final int SEMI = 24;
  public static final int INT = 41;
  public static final int FOR = 38;
  public static final int MINUS = 7;
  public static final int RPAREN = 27;
  public static final int NOT = 13;
  public static final int AND = 11;
  public static final int LT = 17;
  public static final int OR = 12;
  public static final int COMMA = 25;
  public static final int CLASS = 34;
  public static final int PLUSEQ = 21;
  public static final int MINUSEQ = 22;
  public static final int PLUS = 6;
  public static final int IF = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 32;
  public static final int RETURN = 42;
  public static final int RBRACKET = 31;
  public static final int TRUE = 45;
  public static final int RKEY = 29;
  public static final int error = 1;
  public static final int EQEQ = 18;
  public static final int MOD = 10;
  public static final int BREAK = 33;
  public static final int EXTERNINVK = 44;
  public static final int VOID = 43;
  public static final int EQ = 14;
  public static final int TIMES = 8;
  public static final int ELSE = 36;
  public static final int WHILE = 39;
  public static final int FLOAT = 40;
  public static final int FALSE = 46;
  public static final int FLOAT_LITERAL = 3;
  public static final int GT = 16;
  public static final int INT_LITERAL = 2;
  public static final int NOTEQ = 15;
  public static final int IDENTIFIER = 47;
}

