
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 09 23:22:55 ART 2014
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int GTEQ = 19;
  public static final int STRING_LITERAL = 4;
  public static final int LKEY = 27;
  public static final int LBRACKET = 29;
  public static final int LTEQ = 18;
  public static final int UMINUS = 22;
  public static final int LPAREN = 25;
  public static final int SEMI = 23;
  public static final int CONTINUE = 34;
  public static final int INT = 40;
  public static final int FOR = 37;
  public static final int MINUS = 6;
  public static final int RPAREN = 26;
  public static final int NOT = 12;
  public static final int AND = 10;
  public static final int LT = 16;
  public static final int OR = 11;
  public static final int COMMA = 24;
  public static final int CLASS = 33;
  public static final int PLUSEQ = 20;
  public static final int MINUSEQ = 21;
  public static final int PLUS = 5;
  public static final int IF = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int RETURN = 41;
  public static final int RBRACKET = 30;
  public static final int TRUE = 44;
  public static final int RKEY = 28;
  public static final int error = 1;
  public static final int EQEQ = 17;
  public static final int MOD = 9;
  public static final int BREAK = 32;
  public static final int EXTERNINVK = 43;
  public static final int VOID = 42;
  public static final int EQ = 13;
  public static final int TIMES = 7;
  public static final int ELSE = 35;
  public static final int WHILE = 38;
  public static final int FLOAT = 39;
  public static final int FALSE = 45;
  public static final int FLOAT_LITERAL = 3;
  public static final int GT = 15;
  public static final int INT_LITERAL = 2;
  public static final int NOTEQ = 14;
  public static final int IDENTIFIER = 46;
}

